[env]
# Windows用: python-build-standaloneのPython 3.11パス
PYO3_PYTHON = "C:/python-build-standalone/python-3.11.9-x86_64-pc-windows-msvc-shared-pgo/python.exe"

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-L", "C:/python-build-standalone/python-3.11.9-x86_64-pc-windows-msvc-shared-pgo/libs",
    "-L", "C:/python-build-standalone/python-3.11.9-x86_64-pc-windows-msvc-shared-pgo"
]

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-L", "C:/python-build-standalone/python-3.11.9-x86_64-pc-windows-msvc-shared-pgo/libs",
    "-L", "C:/python-build-standalone/python-3.11.9-x86_64-pc-windows-msvc-shared-pgo"
]