[env]
PYO3_PYTHON = "/opt/homebrew/opt/python@3.11/bin/python3.11"

[build]
rustflags = [
    "-L", "/opt/homebrew/opt/python@3.11/lib",
    "-L", "/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib"
]